app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('de', {
        'SMA_TITLE': 'Marokkowoche',
        'CUBE1_TITLE': 'Marokko, wo die Kultur die Kunst inspiriert',
        'CUBE1_INTRO': 'Marokko ist ein Land, wo sich Kunst und Kultur vermischen, eine wirkliche Einladung zum Reisen, ein Gesamtkunstwerk der Begegnung, an dem sich auf vielfältige Art und Weise teilhaben lässt. ',
        'ARTISANAT_TITLE': 'Ein Kunsthandwerk auf der Suche nach dem Schönen',
        'ARTISANAT_TEXT': 'Ein Kunsthandwerk in tausend und einer Facette, wo das Objekt eine menschliche Dimension einnimmt und das authentischste Zeugnis der Suche nach Schönheit ist.',
        'CUISINE_TITLE': 'Eine Kochkunst, die die Frucht verschiedener Einflüsse ist',
        'CUISINE_TEXT': 'Anerkannt wie eine Kunst ist die marokkanische Küche die Frucht phönizischer, kathargischer, römischer, arabischer, andalusischer, türkischer, französischer Einflüsse und bleibt offen für weitere.',
        'PATRIMOINE_TITLE': 'Ein materielles und immaterielles Erbe von großem Reichtum ',
        'A_MONUMENTS_DU_MAROC': 'Marokko, seine Sehenswürdigkeiten und klassischen Monumente ',
        'CONTEMPORAIN_TITLE': 'Eine zeitgenössische Schöpfung, die sich vermischt und ihre eigene Handschrift schafft',
        'CONTEMPORAIN_TEXT': 'Wenn es sich um darstellende Kunst, Literatur, Kino, Videokunst, Theater, Architektur, Mode oder Musik dreht, drückt die zeitgenössische Kunst in Marokko die Widersprüche einer Gesellschaft aus, die zutiefst ihrem geschichtlichen Erbe verbunden ist, die den  Schock der Moderne durchläuft und ihre eigene Handschrift schafft.',
        'CUBE2_TITLE': 'Marokko, ein land wo die Gastfreundschaft eine Lebenskunst offenbart',
        'HOSPITALITE_TITLE': 'Ein Fleck Erde der Gastfreundschaft und der Begegnung',
        'HOSPITALITE_TEXT': 'Gastlich und weltoffen, hat es Marokko verstanden, die Gastfreundschaft zu einem echten Lebensstil zu erheben. Eine Geste der Großzügigkeit, des Gemeinsinns und der Toleranz, die authentische Momente des Miteinanderteilens hervorgebracht hat.',
        'TOURISME_TITLE': 'Ein Tourismus, der seine gastliche Tradition bewahrt',
        'TOURISME_TEXT': 'Charakteristisch für den marokkanischen Tourismus ist seine Authentizität, seine Vielfalt, seine Qualität und seine Nachhaltigkeit, mit der er sich unter den Mittelmeerländern empfiehlt.',
        'PLAN_AZUR': 'Der himmelblaue Plan',
        'PLAN_AZUR_TEXT': 'wurde eingerichtet, um eine Reihe von wirtschaftlich tragfähigen und soziokulturellen Qualitätsunterkünften zu schaffen, die die Prinzipien der nachhaltigen Entwicklung unter den Aspekten des Umweltschutzes respektieren.',
        'A_MINISTER_TOURISME': 'Marokkanisches Tourismusministerium',
        'CUBE3_TITLE': 'Marokko, ein Land voller Geschichte',
        'CIVILISATION_TITLE': 'Ein Land, in dem sich Zivilisationen vereinen',
        'CIVILISATION_TEXT': 'Vom Königreich der Mauren… über das Römische Reich bis hin zur Islamisierung, Marokko ist ein wahrer Schmelztiegel der Zivilisationen, die seine vielfältige Identität geschaffen haben.',
        'COMPOSANTS_TITLE': 'Ein Land mit vielfältigen Kulturen',
        'COMPOSANTS_TEXT': 'Es sind die verschiedenen Kulturen Marokkos wie die amazighische, jüdisch-christliche, arabisch-muslimische und afro-saharische, die seine Besonderheit, seine Einzigartigkeit, seine Vielfalt und seinen kulturellen Reichtum prägen.',
        'REFORMES_TITLE': 'Ein Land, das historische Reformen kennengelernt hat',
        'REFORMES_TEXT1': 'Gelegen in einer Region, die von den Ereignissen des Arabischen Frühlings durcheinander gewirbelt wurde, hat das Königreich seine Stabilität und seinen sozialen Zusammenhalt gefestigt, indem es politische und bedeutende wirtschaftliche Reformen vorangetrieben hat.',
        'REFORMES_TEXT2': 'Die neue Verfassung beinhaltet die vollkommene Gleichstellung von Männern und Frauen.',

        'EN_SAVOIR_PLUS': 'Mehr Informationen :',

    }).translations('ar', {
        'SMA_TITLE': 'أسبوع المغرب في ألمانيا',
        'CUBE1_TITLE': 'المغرب، حيث الثقافة تلهم الفن',
        'CUBE1_INTRO': 'المغرب بلد حيث تتماها الثقافة بالفن، إنه دعوة صريحة للسفر، عطر اللقاء الذي يمنح نفسه ليتم تقاسمه على أكثر من نقطة',
        'ARTISANAT_TITLE': 'صناعة تقليدية في بحث مستمر على الجميل',
        'ARTISANAT_TEXT': 'صناعة تقليدية بألف وجه ووجه، حيث الموضوع يأخذ بعده الإنساني وهو حليل أصيل على بحثها المستمر عن الجمال',
        'CUISINE_TITLE': 'فن طبخ راق، هو باكورة مؤثرات عديدة',
        'CUISINE_TEXT': 'اشتهر فن الطبخ المغربي كفن قائم بذاته، فهو نتاج مؤثرات عديدة فينيقية، قرطاجية، رومانية، عربية، أندلسية، تركية، فرنسية، وتبقى منفتحة على مؤثرات أخرى',
        'PATRIMOINE_TITLE': 'تراث مادي ولا مادي، غني ومتنوع',
        'A_MONUMENTS_DU_MAROC': 'المواقع الخاصة بالمآثر المغربية',
        'CONTEMPORAIN_TITLE': 'إبداع معاصر بألوان عديدة وقادر على خلق بصمته الخاصة',
        'CONTEMPORAIN_TEXT': 'سواء تعلق الأمر بالرسوم التشكيلية أو الأداب، السينما، الفيديو، المسرح، الهندسة، الموضة، الفن المغربي المعاصر يعبر عن تناقضات مجتمع يرتبط إلى تاريخ عريق لتراثه الذي يسعى نحو خلق بصمة خاصة به',
        'CUBE2_TITLE': 'المغرب، بلد حسن الضيافة حيث الكرم يعبر عن فن العيش',
        'HOSPITALITE_TITLE': 'أرض حسن الضيافة واللقاءات',
        'HOSPITALITE_TEXT': 'بلد حسن الاستقبال واللقاءات، فالمغرب عرف كيف يجعل من حسن الضيافة واحدة من أهم أساسيات فن العيش، لمسات تعبر عن الكرم، التضامن والتسامح والتي تجعلكم تعيشون فيه لحظات لا مثيل لها من الإحساس بالمشاركة',
        'TOURISME_TITLE': 'سياحة تؤكد عن عراقة تقليد الاستقبال',
        'TOURISME_TEXT': 'السياحة المغربية رمز للأصالة، التنوع، الجودة والاستمرارية، تفرض نفسها كمرجع أساسي لبلدان البحر الأبيض المتوسط',
        'PLAN_AZUR': 'المخطط الأزرق',
        'PLAN_AZUR_TEXT': 'تم إدراجه لخلق مجموعة سلاسل فندقية ذات جودة عالية، والتي تحترم شروط التطور المستمر في إطار جوانبه البيئية والاقتصادية والسوسيوثقافية',
        'A_MINISTER_TOURISME': 'وزارة السياحة المغربية',
        'CUBE3_TITLE': 'المغرب ، أرض التاريخ',
        'CIVILISATION_TITLE': 'المغرب مهد الحضارات',
        'CIVILISATION_TEXT': 'من أرض المغربية، إلى الرومانية ، إلى الإسلامية، هذا هو المغرب، المهد الحقيقي لحضارات ساهمت في تشكيل هويته الجماعية',
        'COMPOSANTS_TITLE': 'بلد بأعراق متنوعة',
        'COMPOSANTS_TEXT': 'من هذه الأعراق المتنوعة بين الأمازيغية، اليهودية المسيحية، العربية الإسلامية، الإفريقية الصحراوية، استطاع المغرب بناء خصوصيته، تفرده، تنوعه وغناه الحضاري',
        'REFORMES_TITLE': 'بلد عرف إصلاحات تاريخية',
        'REFORMES_TEXT1': 'مزروع في قلب منطقة ما يعرف بالربيع العربي، إلا أنه استطاع الحفاظ على استقراره وتماسكه الاجتماعي وذلك بالسبق نحو إصلاحات سياسية واقتصادية رائدة',
        'REFORMES_TEXT2': 'الصياغة الجديدة لدستور جديد تؤكد على مساواة مطلقة بين الرجال والنساء',

        'EN_SAVOIR_PLUS': 'للمزيد من المعلومات',
    });

    $translateProvider.preferredLanguage('ar');
}]);